version: "3.3"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    logging:
      driver: json-file
    ports:
      - 5432:5432
